In [1]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 122.8 MB/s eta 0:00:00m eta 0:00:010:01

[notice] A new release of pip available: 22.1.2 -> 22.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
v1 = np.array([1,2,3,4])
v1

array([1, 2, 3, 4])

In [4]:
type(v1)

numpy.ndarray

In [5]:
v1.dtype

dtype('int64')

In [7]:
v1.shape

(4,)

In [10]:
v2 = np.array([1,2,4.3, '안녕씨발'])
v2

array(['1', '2', '4.3', '안녕씨발'], dtype='<U32')

In [11]:
v2.dtype

dtype('<U32')

In [12]:
v1.shape

(4,)

In [13]:
sample_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
sample_matrix[0]

array([1, 2, 3])

In [17]:
sample_matrix[0,2]

3

In [18]:
sample_matrix[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [20]:
sample_matrix[:,2]

[array([3, 6, 9])]